# Traffic Signal RL Reproducibility Notebook

This notebook is the main reproducibility entry point for the Traffic Signal Control using Reinforcement Learning project.

It verifies the project structure, installs CityFlow from source with the required CMake compatibility patches, runs available experiment scripts, and summarizes generated result files.

**Before opening this notebook, create and activate the Conda environment:**

```bash
conda env create -f environment.yml
conda activate traffic-rl
python -m ipykernel install --user --name traffic-rl --display-name "traffic-rl"
```
Then select the `traffic-rl` kernel for this notebook. If you do not see it, restart your editor.

## 1. Locate the Project Root

This cell finds the repository root by searching for common project files and folders. It also adds the project root to `PYTHONPATH` so local modules can be imported.

In [1]:
from pathlib import Path
import os
import sys
import subprocess
import shutil
import textwrap
import json
import glob

NOTEBOOK_START = Path.cwd().resolve()

PROJECT_MARKERS = [
    "environment.yml",
    "env/cityflow_env.py",
    "scripts",
]

def find_project_root(start: Path) -> Path:
    for candidate in [start] + list(start.parents):
        if any((candidate / marker).exists() for marker in PROJECT_MARKERS):
            return candidate
    return start

PROJECT_ROOT = find_project_root(NOTEBOOK_START)
os.chdir(PROJECT_ROOT)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

existing_pythonpath = os.environ.get("PYTHONPATH", "")
os.environ["PYTHONPATH"] = str(PROJECT_ROOT) + (os.pathsep + existing_pythonpath if existing_pythonpath else "")

print("Notebook started in:", NOTEBOOK_START)
print("Project root:", PROJECT_ROOT)
print("Python executable:", sys.executable)

Notebook started in: /Users/achakrav6/Desktop/new-repo-asi
Project root: /Users/achakrav6/Desktop/new-repo-asi
Python executable: /opt/homebrew/Caskroom/miniconda/base/envs/traffic-rl/bin/python

## 2. Verify Expected Repository Structure

This confirms that the main project folders and files are present. Missing optional folders are reported as warnings instead of stopping the notebook.

In [2]:
expected_paths = [
    "environment.yml",
    "env/cityflow_env.py",
    "scripts",
    "scripts/baseline",
    "scripts/q_learning_experiments",
    "scripts/stable_baselines",
    "scripts/dqn_lstm",
    "scripts/lstm_vector",
]

missing = []
for rel_path in expected_paths:
    path = PROJECT_ROOT / rel_path
    status = "FOUND" if path.exists() else "MISSING"
    print(f"{status:8} {rel_path}")
    if not path.exists():
        missing.append(rel_path)

if missing:
    print("Some expected paths are missing. This is okay if those parts were not included in your final repo.")
else:
    print("Repository structure looks good.")

FOUND    environment.yml
FOUND    env/cityflow_env.py
FOUND    scripts
FOUND    scripts/baseline
FOUND    scripts/q_learning_experiments
FOUND    scripts/stable_baselines
FOUND    scripts/dqn_lstm
FOUND    scripts/lstm_vector
Repository structure looks good.

## 3. Helper Functions

These helpers run shell commands and Python scripts from the project root while printing clear output.

In [9]:
from types import SimpleNamespace


def run(cmd, cwd=PROJECT_ROOT, check=True, env=None):
    merged_env = os.environ.copy()
    merged_env.setdefault("PYTHONUNBUFFERED", "1")
    if env:
        merged_env.update(env)
    print("$", " ".join(map(str, cmd)))
    proc = subprocess.Popen(
        list(map(str, cmd)),
        cwd=cwd,
        env=merged_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    chunks = []
    if proc.stdout is not None:
        for line in proc.stdout:
            print(line, end="")
            sys.stdout.flush()
            chunks.append(line)
    proc.wait()
    full_out = "".join(chunks)
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"Command failed with exit code {proc.returncode}: {' '.join(map(str, cmd))}"
        )
    return SimpleNamespace(returncode=proc.returncode, stdout=full_out)


def run_python_script(script_path, required=False, extra_args=None):
    print(f"Running: {script_path}")
    script = PROJECT_ROOT / script_path
    if not script.exists():
        msg = f"Skipping missing script: {script_path}"
        if required:
            raise FileNotFoundError(msg)
        print(msg)
        return None
    args = [sys.executable, "-u", str(script)]
    if extra_args:
        args.extend(extra_args)
    return run(args, check=required)

## 4. Install or Verify CityFlow

CityFlow is built from source because this project uses the CityFlow simulator directly.

Newer CMake versions may fail on CityFlow's older CMake settings, so this cell patches all CityFlow CMake files that require versions older than 3.5 before installation.

This cell is idempotent: if `cityflow` is already importable, it skips the build.

In [10]:
import importlib.util
import re

FORCE_REINSTALL_CITYFLOW = False
CITYFLOW_DIR = PROJECT_ROOT / "CityFlow"
CITYFLOW_REPO = "https://github.com/cityflow-project/CityFlow.git"


def cityflow_is_available() -> bool:
    try:
        import cityflow  # noqa: F401
        return True
    except Exception:
        return False


def patch_cmake_versions(cityflow_dir: Path):
    cmake_files = list(cityflow_dir.rglob("CMakeLists.txt")) + list(cityflow_dir.rglob("*.cmake"))
    patched = []
    pattern = re.compile(r"cmake_minimum_required\(VERSION\s+([0-9]+(?:\.[0-9]+)*)\)")

    for file_path in cmake_files:
        text = file_path.read_text(errors="ignore")

        def replace(match):
            version = match.group(1)
            parts = tuple(int(p) for p in version.split("."))
            if parts < (3, 5):
                return "cmake_minimum_required(VERSION 3.5)"
            return match.group(0)

        new_text = pattern.sub(replace, text)
        if new_text != text:
            backup = file_path.with_suffix(file_path.suffix + ".bak")
            if not backup.exists():
                backup.write_text(text)
            file_path.write_text(new_text)
            patched.append(file_path.relative_to(cityflow_dir))

    print(f"Patched {len(patched)} CMake file(s).")
    for p in patched:
        print(" -", p)


if cityflow_is_available() and not FORCE_REINSTALL_CITYFLOW:
    import cityflow
    print("CityFlow is already installed.")
    print("cityflow module:", cityflow)
else:
    if not shutil.which("git"):
        raise RuntimeError("git is required. Install it through Conda or your system package manager.")
    if not shutil.which("cmake"):
        raise RuntimeError("cmake is required. It should be installed by environment.yml.")

    if not CITYFLOW_DIR.exists():
        run(["git", "clone", CITYFLOW_REPO, str(CITYFLOW_DIR)])
    else:
        print("CityFlow directory already exists:", CITYFLOW_DIR)

    run(["git", "submodule", "update", "--init", "--recursive"], cwd=CITYFLOW_DIR)
    patch_cmake_versions(CITYFLOW_DIR)

    for artifact in ["build", "dist"]:
        path = CITYFLOW_DIR / artifact
        if path.exists():
            shutil.rmtree(path)
    for egg_info in CITYFLOW_DIR.glob("*.egg-info"):
        shutil.rmtree(egg_info)

    run(
        [sys.executable, "-m", "pip", "install", "."],
        cwd=CITYFLOW_DIR,
        env={"CMAKE_ARGS": "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"},
    )

    import cityflow
    print("CityFlow installed successfully.")
    print("cityflow module:", cityflow)

CityFlow is already installed.
cityflow module: <module 'cityflow' from '/opt/homebrew/Caskroom/miniconda/base/envs/traffic-rl/lib/python3.10/site-packages/cityflow.cpython-310-darwin.so'>

## 5. Create Output Folders

Experiment scripts write outputs to `results/`, `figures/`, `logs/`, and `models/`.

In [11]:
for folder in ["results", "figures", "logs", "models"]:
    (PROJECT_ROOT / folder).mkdir(exist_ok=True)
print("Output folders are ready.")

Output folders are ready.

## 6. Import the Custom CityFlow Environment

This verifies that the project environment wrapper can be imported.

In [12]:
try:
    from env.cityflow_env import CityFlowEnv
    print("Imported CityFlowEnv successfully:", CityFlowEnv)
except Exception as exc:
    print("Could not import CityFlowEnv.")
    print("Error:", repr(exc))
    raise

Imported CityFlowEnv successfully: <class 'env.cityflow_env.CityFlowEnv'>

## 7. Configure Experiment Run Mode

Use `QUICK_RUN = True` for a fast smoke test. Set `QUICK_RUN = False` to run the full available experiment pipeline.

Some scripts may take a long time depending on the number of episodes and the size of the CityFlow dataset.

In [18]:
QUICK_RUN = True
RUN_Q_LEARNING = True
RUN_STABLE_BASELINES = False if QUICK_RUN else True
RUN_DQN_LSTM = False if QUICK_RUN else True
RUN_LSTM_VECTOR = False if QUICK_RUN else True

print("QUICK_RUN:", QUICK_RUN)
print("RUN_Q_LEARNING:", RUN_Q_LEARNING)
print("RUN_STABLE_BASELINES:", RUN_STABLE_BASELINES)
print("RUN_DQN_LSTM:", RUN_DQN_LSTM)
print("RUN_LSTM_VECTOR:", RUN_LSTM_VECTOR)

QUICK_RUN: True
RUN_Q_LEARNING: True
RUN_STABLE_BASELINES: False
RUN_DQN_LSTM: False
RUN_LSTM_VECTOR: False

## 8. List Available Scripts

This makes the notebook robust to small repository differences by showing exactly which scripts are available.

In [13]:
script_files = sorted((PROJECT_ROOT / "scripts").rglob("*.py")) if (PROJECT_ROOT / "scripts").exists() else []
print(f"Found {len(script_files)} Python script(s) under scripts/.")
for script in script_files:
    print(script.relative_to(PROJECT_ROOT))

Found 31 Python script(s) under scripts/.
scripts/baseline/plot_baseline_results.py
scripts/baseline/run_baseline.py
scripts/dqn_lstm/collect_lstm_data.py
scripts/dqn_lstm/train.py
scripts/dqn_lstm/train_dqn_with_lstm.py
scripts/dqn_lstm/train_lstm.py
scripts/lstm_vector/lstm_vector_train.py
scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_default_reward.py
scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_delta_wait.py
scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_wait_small_vehicle.py
scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_wait_vehicle.py
scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_default_reward.py
scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_delta_wait.py
scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_wait_small_vehicle.py
scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_wait_vehicle.py
scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_default_reward.py
scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_delta_wait.py
scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_wait_small_vehicle.py
scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_wait_vehicle.py
scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_default_reward.py
scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_delta_wait.py
scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_wait_small_vehicle.py
scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_wait_vehicle.py
scripts/q_learning_experiments/compare_hangzhou_models.py
scripts/run_simulation.py
scripts/stable_baselines/base_agent.py
scripts/stable_baselines/compare_sb3_models.py
scripts/stable_baselines/env_wrapper.py
scripts/stable_baselines/train_a2c.py
scripts/stable_baselines/train_dqn.py
scripts/stable_baselines/train_ppo.py

## 9. Prepare Dataset Location for CityFlow Scripts

Some scripts expect the Hangzhou dataset either in the project root or inside the `CityFlow/` directory. This cell copies the dataset into `CityFlow/` if needed.

In [14]:
source_candidates = [
    PROJECT_ROOT / "hangzhou_datasets",
    PROJECT_ROOT / "data" / "hangzhou_datasets",
]

target_dir = PROJECT_ROOT / "CityFlow" / "hangzhou_datasets"

if target_dir.exists():
    print("Dataset already available at:", target_dir)
else:
    copied = False
    for source in source_candidates:
        if source.exists():
            shutil.copytree(source, target_dir)
            print(f"Copied dataset from {source} to {target_dir}")
            copied = True
            break
    if not copied:
        print("No Hangzhou dataset folder found in the expected locations.")
        print("If scripts fail with missing roadnet/flow/config files, check dataset paths in your repo.")

Dataset already available at: /Users/achakrav6/Desktop/new-repo-asi/CityFlow/hangzhou_datasets

## 10. Run Q-Learning Experiments

The Q-learning experiments are organized by state representation and reward function. Each block runs one group of experiments and saves its results to the `results/` folder.

Each Q-learning configuration (e.g., bucketed, capped, with/without phase, different reward functions) is run as a separate block.

- **Runtime:**  
  Each configuration typically takes **~20 minutes** to complete, depending on system performance.  
  Since multiple configurations are run sequentially, the full Q-learning section may take **1–2+ hours total**.

- **Where results are saved:**  
  All outputs are saved inside the `results/` directory, organized by: `results/<dataset_name>/<experiment_name>/`


---

### Output Files

Each experiment generates the following files:

#### 1. `q_learning_training.csv`
- Logs training progress across episodes
- Key columns include:
- `episode`
- `total_reward`
- `mean_reward_per_decision`
- `final_waiting`
- `avg_waiting`
- `final_avg_travel_time`
- `epsilon`

---

#### 2. `q_learning_trace.csv`
- Records a single evaluation run using the learned policy
- Each row corresponds to one decision step
- Includes:
- chosen action / phase
- state representation (e.g., bucketed queues)
- reward at each step
- total waiting time
- vehicle count
- average travel time

---

#### 3. `q_table.pkl`
- Serialized Q-table (learned policy)
- Can be loaded later for evaluation without retraining

---

#### 4. `runtime_config.json`
- The exact simulation configuration used for the run
- Ensures reproducibility

---

#### 5. `summary_all_datasets.csv` (generated after all runs, in a separate folder for the experiment)
- Aggregated summary across all datasets
- Includes:
- total reward
- final waiting time
- average waiting time
- travel time

### Bucketed No Phase

In [ ]:
bucketed_no_phase_scripts = [
    "scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_default_reward.py",
    "scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_delta_wait.py",
    "scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_wait_small_vehicle.py",
    "scripts/q_learning_experiments/bucketed_no_phase/train_bucketed_no_phase_wait_vehicle.py",
]

for script in bucketed_no_phase_scripts:
    run_python_script(script, required=True)

### Bucked With Phase

In [ ]:
bucketed_with_phase_scripts = [
    "scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_default_reward.py",
    "scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_delta_wait.py",
    "scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_wait_small_vehicle.py",
    "scripts/q_learning_experiments/bucketed_with_phase/train_bucketed_with_phase_wait_vehicle.py",
]

for script in bucketed_with_phase_scripts:
    run_python_script(script, required=True)

### Capped No Phase

In [ ]:
capped_no_phase_scripts = [
    "scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_default_reward.py",
    "scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_delta_wait.py",
    "scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_wait_small_vehicle.py",
    "scripts/q_learning_experiments/capped_no_phase/train_capped_no_phase_wait_vehicle.py",
]

for script in capped_no_phase_scripts:
    run_python_script(script, required=True)

### Capped With Phase

In [ ]:
capped_with_phase_scripts = [
    "scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_default_reward.py",
    "scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_delta_wait.py",
    "scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_wait_small_vehicle.py",
    "scripts/q_learning_experiments/capped_with_phase/train_capped_with_phase_wait_vehicle.py",
]

for script in capped_with_phase_scripts:
    run_python_script(script, required=True)

### Final Q-learning Comparison
This script compares the Hangzhou Q-learning model variants after the individual state and reward experiments have been run.

In [19]:
comparison_script = "scripts/q_learning_experiments/compare_hangzhou_models.py"

run_python_script(comparison_script, required=True)

Running: scripts/q_learning_experiments/compare_hangzhou_models.py
$ /opt/homebrew/Caskroom/miniconda/base/envs/traffic-rl/bin/python -u /Users/achakrav6/Desktop/new-repo-asi/scripts/q_learning_experiments/compare_hangzhou_models.py

======================================================================
Dataset: hangzhou_1x1_bc-tyc_18041607_1h
Config path: CityFlow/hangzhou_datasets/hangzhou_1x1_bc-tyc_18041607_1h/config.json
Intersection id: intersection_1_1
Lane ids: ['road_0_1_0_0', 'road_0_1_0_1', 'road_1_0_1_0', 'road_1_0_1_1', 'road_1_2_3_0', 'road_1_2_3_1', 'road_2_1_2_0', 'road_2_1_2_1']
Phase ids: [1, 2, 3, 4, 5, 6, 7, 8]

Comparison:
fixed_cycle                              | reward=  -3238.00 | avg_wait=   22.49 | final_wait=   38.00 | travel_time=   76.64
bucketed_no_phase_default                | reward=  -1817.00 | avg_wait=   12.62 | final_wait=   58.00 | travel_time=   58.30
bucketed_no_phase_delta_wait             | reward=  -1072.00 | avg_wait=    7.44 | final_wait=   21.00 | travel_time=   57.14
bucketed_no_phase_wait_small_vehicle     | reward=   -906.00 | avg_wait=    6.29 | final_wait=   21.00 | travel_time=   56.28
bucketed_no_phase_wait_vehicle           | reward=  -2441.00 | avg_wait=   16.95 | final_wait=   77.00 | travel_time=   61.82
capped_no_phase_default_reward           | reward=  -2127.00 | avg_wait=   14.77 | final_wait=   40.00 | travel_time=   63.71
capped_no_phase_delta_wait               | reward=   -449.00 | avg_wait=    3.12 | final_wait=    5.00 | travel_time=   54.99
capped_no_phase_wait_small_vehicle       | reward=  -2000.00 | avg_wait=   13.89 | final_wait=   29.00 | travel_time=   69.20
capped_no_phase_wait_vehicle             | reward=  -2140.00 | avg_wait=   14.86 | final_wait=   33.00 | travel_time=   71.89
bucketed_with_phase_default_reward       | reward=  -2168.00 | avg_wait=   15.06 | final_wait=   42.00 | travel_time=   68.88
bucketed_with_phase_delta_wait           | reward=   -578.00 | avg_wait=    4.01 | final_wait=    7.00 | travel_time=   56.38
bucketed_with_phase_wait_small_vehicle   | reward=  -1562.00 | avg_wait=   10.85 | final_wait=   22.00 | travel_time=   68.33
bucketed_with_phase_wait_vehicle         | reward=  -3899.00 | avg_wait=   27.08 | final_wait=   47.00 | travel_time=   75.98
capped_with_phase_default_reward         | reward=  -4017.00 | avg_wait=   27.90 | final_wait=   30.00 | travel_time=   88.75
capped_with_phase_delta_wait             | reward=   -581.00 | avg_wait=    4.03 | final_wait=    7.00 | travel_time=   55.36
capped_with_phase_wait_small_vehicle     | reward=  -4617.00 | avg_wait=   32.06 | final_wait=   65.00 | travel_time=   84.03
capped_with_phase_wait_vehicle           | reward=  -2315.00 | avg_wait=   16.08 | final_wait=   25.00 | travel_time=   74.64

======================================================================
Dataset: hangzhou_1x1_bc-tyc_18041608_1h
Config path: CityFlow/hangzhou_datasets/hangzhou_1x1_bc-tyc_18041608_1h/config.json
Intersection id: intersection_1_1
Lane ids: ['road_0_1_0_0', 'road_0_1_0_1', 'road_1_0_1_0', 'road_1_0_1_1', 'road_1_2_3_0', 'road_1_2_3_1', 'road_2_1_2_0', 'road_2_1_2_1']
Phase ids: [1, 2, 3, 4, 5, 6, 7, 8]

Comparison:
fixed_cycle                              | reward=  -7463.00 | avg_wait=   51.83 | final_wait=   76.00 | travel_time=   98.95
bucketed_no_phase_default                | reward=  -6189.00 | avg_wait=   42.98 | final_wait=   63.00 | travel_time=   95.15
bucketed_no_phase_delta_wait             | reward=  -3998.00 | avg_wait=   27.76 | final_wait=   26.00 | travel_time=   76.89
bucketed_no_phase_wait_small_vehicle     | reward=  -4736.00 | avg_wait=   32.89 | final_wait=   56.00 | travel_time=   76.41
bucketed_no_phase_wait_vehicle           | reward=  -6702.00 | avg_wait=   46.54 | final_wait=  102.00 | travel_time=   91.61
capped_no_phase_default_reward           | reward=  -5955.00 | avg_wait=   41.35 | final_wait=   51.00 | travel_time=   92.52
capped_no_phase_delta_wait               | reward=  -4179.00 | avg_wait=   29.02 | final_wait=   38.00 | travel_time=   77.22
capped_no_phase_wait_small_vehicle       | reward=  -5229.00 | avg_wait=   36.31 | final_wait=   46.00 | travel_time=   85.24
capped_no_phase_wait_vehicle             | reward=  -5874.00 | avg_wait=   40.79 | final_wait=   45.00 | travel_time=   92.68
bucketed_with_phase_default_reward       | reward=  -5299.00 | avg_wait=   36.80 | final_wait=   40.00 | travel_time=   88.68
bucketed_with_phase_delta_wait           | reward=  -3772.00 | avg_wait=   26.19 | final_wait=   42.00 | travel_time=   75.48
bucketed_with_phase_wait_small_vehicle   | reward=  -6167.00 | avg_wait=   42.83 | final_wait=   35.00 | travel_time=   93.16
bucketed_with_phase_wait_vehicle         | reward=  -5911.00 | avg_wait=   41.05 | final_wait=   53.00 | travel_time=   88.15
capped_with_phase_default_reward         | reward=  -6267.00 | avg_wait=   43.52 | final_wait=   52.00 | travel_time=   91.87
capped_with_phase_delta_wait             | reward=  -3818.00 | avg_wait=   26.51 | final_wait=   39.00 | travel_time=   75.80
capped_with_phase_wait_small_vehicle     | reward=  -7224.00 | avg_wait=   50.17 | final_wait=   42.00 | travel_time=   99.39
capped_with_phase_wait_vehicle           | reward=  -6894.00 | avg_wait=   47.88 | final_wait=   62.00 | travel_time=   95.48

======================================================================
Dataset: hangzhou_1x1_bc-tyc_18041610_1h
Config path: CityFlow/hangzhou_datasets/hangzhou_1x1_bc-tyc_18041610_1h/config.json
Intersection id: intersection_1_1
Lane ids: ['road_0_1_0_0', 'road_0_1_0_1', 'road_1_0_1_0', 'road_1_0_1_1', 'road_1_2_3_0', 'road_1_2_3_1', 'road_2_1_2_0', 'road_2_1_2_1']
Phase ids: [1, 2, 3, 4, 5, 6, 7, 8]

Comparison:
fixed_cycle                              | reward=  -6621.00 | avg_wait=   45.98 | final_wait=   74.00 | travel_time=   97.49
bucketed_no_phase_default                | reward=  -5273.00 | avg_wait=   36.62 | final_wait=   57.00 | travel_time=   85.11
bucketed_no_phase_delta_wait             | reward=  -1721.00 | avg_wait=   11.95 | final_wait=   14.00 | travel_time=   69.02
bucketed_no_phase_wait_small_vehicle     | reward=  -3586.00 | avg_wait=   24.90 | final_wait=   51.00 | travel_time=   77.66
bucketed_no_phase_wait_vehicle           | reward=  -4602.00 | avg_wait=   31.96 | final_wait=   45.00 | travel_time=   82.72
capped_no_phase_default_reward           | reward=  -5477.00 | avg_wait=   38.03 | final_wait=   48.00 | travel_time=   88.23
capped_no_phase_delta_wait               | reward=  -1640.00 | avg_wait=   11.39 | final_wait=   18.00 | travel_time=   66.77
capped_no_phase_wait_small_vehicle       | reward=  -5032.00 | avg_wait=   34.94 | final_wait=   60.00 | travel_time=   83.32
capped_no_phase_wait_vehicle             | reward=  -5417.00 | avg_wait=   37.62 | final_wait=   54.00 | travel_time=   93.14
bucketed_with_phase_default_reward       | reward=  -4604.00 | avg_wait=   31.97 | final_wait=   56.00 | travel_time=   85.98
bucketed_with_phase_delta_wait           | reward=  -1952.00 | avg_wait=   13.56 | final_wait=   12.00 | travel_time=   72.92
bucketed_with_phase_wait_small_vehicle   | reward=  -5972.00 | avg_wait=   41.47 | final_wait=   66.00 | travel_time=   95.13
bucketed_with_phase_wait_vehicle         | reward=  -5254.00 | avg_wait=   36.49 | final_wait=   69.00 | travel_time=   88.26
capped_with_phase_default_reward         | reward=  -5663.00 | avg_wait=   39.33 | final_wait=   56.00 | travel_time=   89.30
capped_with_phase_delta_wait             | reward=  -1566.00 | avg_wait=   10.88 | final_wait=   27.00 | travel_time=   67.60
capped_with_phase_wait_small_vehicle     | reward=  -6005.00 | avg_wait=   41.70 | final_wait=   67.00 | travel_time=   89.74
capped_with_phase_wait_vehicle           | reward=  -5590.00 | avg_wait=   38.82 | final_wait=   40.00 | travel_time=   94.94

Saved combined comparison:
  results/hangzhou_comparison/comparison_all_datasets.csv

namespace(returncode=0,
          stdout="\n======================================================================\nDataset: hangzhou_1x1_bc-tyc_18041607_1h\nConfig path: CityFlow/hangzhou_datasets/hangzhou_1x1_bc-tyc_18041607_1h/config.json\nIntersection id: intersection_1_1\nLane ids: ['road_0_1_0_0', 'road_0_1_0_1', 'road_1_0_1_0', 'road_1_0_1_1', 'road_1_2_3_0', 'road_1_2_3_1', 'road_2_1_2_0', 'road_2_1_2_1']\nPhase ids: [1, 2, 3, 4, 5, 6, 7, 8]\n\nComparison:\nfixed_cycle                              | reward=  -3238.00 | avg_wait=   22.49 | final_wait=   38.00 | travel_time=   76.64\nbucketed_no_phase_default                | reward=  -1817.00 | avg_wait=   12.62 | final_wait=   58.00 | travel_time=   58.30\nbucketed_no_phase_delta_wait             | reward=  -1072.00 | avg_wait=    7.44 | final_wait=   21.00 | travel_time=   57.14\nbucketed_no_phase_wait_small_vehicle     | reward=   -906.00 | avg_wait=    6.29 | final_wait=   21.00 | travel_time=   56.28\nbucketed_no_phase_wait_vehicle           | reward=  -2441.00 | avg_wait=   16.95 | final_wait=   77.00 | travel_time=   61.82\ncapped_no_phase_default_reward           | reward=  -2127.00 | avg_wait=   14.77 | final_wait=   40.00 | travel_time=   63.71\ncapped_no_phase_delta_wait               | reward=   -449.00 | avg_wait=    3.12 | final_wait=    5.00 | travel_time=   54.99\ncapped_no_phase_wait_small_vehicle       | reward=  -2000.00 | avg_wait=   13.89 | final_wait=   29.00 | travel_time=   69.20\ncapped_no_phase_wait_vehicle             | reward=  -2140.00 | avg_wait=   14.86 | final_wait=   33.00 | travel_time=   71.89\nbucketed_with_phase_default_reward       | reward=  -2168.00 | avg_wait=   15.06 | final_wait=   42.00 | travel_time=   68.88\nbucketed_with_phase_delta_wait           | reward=   -578.00 | avg_wait=    4.01 | final_wait=    7.00 | travel_time=   56.38\nbucketed_with_phase_wait_small_vehicle   | reward=  -1562.00 | avg_wait=   10.85 | final_wait=   22.00 | travel_time=   68.33\nbucketed_with_phase_wait_vehicle         | reward=  -3899.00 | avg_wait=   27.08 | final_wait=   47.00 | travel_time=   75.98\ncapped_with_phase_default_reward         | reward=  -4017.00 | avg_wait=   27.90 | final_wait=   30.00 | travel_time=   88.75\ncapped_with_phase_delta_wait             | reward=   -581.00 | avg_wait=    4.03 | final_wait=    7.00 | travel_time=   55.36\ncapped_with_phase_wait_small_vehicle     | reward=  -4617.00 | avg_wait=   32.06 | final_wait=   65.00 | travel_time=   84.03\ncapped_with_phase_wait_vehicle           | reward=  -2315.00 | avg_wait=   16.08 | final_wait=   25.00 | travel_time=   74.64\n\n======================================================================\nDataset: hangzhou_1x1_bc-tyc_18041608_1h\nConfig path: CityFlow/hangzhou_datasets/hangzhou_1x1_bc-tyc_18041608_1h/config.json\nIntersection id: intersection_1_1\nLane ids: ['road_0_1_0_0', 'road_0_1_0_1', 'road_1_0_1_0', 'road_1_0_1_1', 'road_1_2_3_0', 'road_1_2_3_1', 'road_2_1_2_0', 'road_2_1_2_1']\nPhase ids: [1, 2, 3, 4, 5, 6, 7, 8]\n\nComparison:\nfixed_cycle                              | reward=  -7463.00 | avg_wait=   51.83 | final_wait=   76.00 | travel_time=   98.95\nbucketed_no_phase_default                | reward=  -6189.00 | avg_wait=   42.98 | final_wait=   63.00 | travel_time=   95.15\nbucketed_no_phase_delta_wait             | reward=  -3998.00 | avg_wait=   27.76 | final_wait=   26.00 | travel_time=   76.89\nbucketed_no_phase_wait_small_vehicle     | reward=  -4736.00 | avg_wait=   32.89 | final_wait=   56.00 | travel_time=   76.41\nbucketed_no_phase_wait_vehicle           | reward=  -6702.00 | avg_wait=   46.54 | final_wait=  102.00 | travel_time=   91.61\ncapped_no_phase_default_reward           | reward=  -5955.00 | avg_wait=   41.35 | final_wait=   51.00 | travel_time=   92.52\ncapped_no_phase_delta_wait               | reward=  -4179.00 | avg_wait=   29.02 | final_wait=   38.00 | travel_time=   77.22\ncapped_no_phase_wait_small_vehicle       | reward=  -5229.00 | avg_wait=   36.31 | final_wait=   46.00 | travel_time=   85.24\ncapped_no_phase_wait_vehicle             | reward=  -5874.00 | avg_wait=   40.79 | final_wait=   45.00 | travel_time=   92.68\nbucketed_with_phase_default_reward       | reward=  -5299.00 | avg_wait=   36.80 | final_wait=   40.00 | travel_time=   88.68\nbucketed_with_phase_delta_wait           | reward=  -3772.00 | avg_wait=   26.19 | final_wait=   42.00 | travel_time=   75.48\nbucketed_with_phase_wait_small_vehicle   | reward=  -6167.00 | avg_wait=   42.83 | final_wait=   35.00 | travel_time=   93.16\nbucketed_with_phase_wait_vehicle         | reward=  -5911.00 | avg_wait=   41.05 | final_wait=   53.00 | travel_time=   88.15\ncapped_with_phase_default_reward         | reward=  -6267.00 | avg_wait=   43.52 | final_wait=   52.00 | travel_time=   91.87\ncapped_with_phase_delta_wait             | reward=  -3818.00 | avg_wait=   26.51 | final_wait=   39.00 | travel_time=   75.80\ncapped_with_phase_wait_small_vehicle     | reward=  -7224.00 | avg_wait=   50.17 | final_wait=   42.00 | travel_time=   99.39\ncapped_with_phase_wait_vehicle           | reward=  -6894.00 | avg_wait=   47.88 | final_wait=   62.00 | travel_time=   95.48\n\n======================================================================\nDataset: hangzhou_1x1_bc-tyc_18041610_1h\nConfig path: CityFlow/hangzhou_datasets/hangzhou_1x1_bc-tyc_18041610_1h/config.json\nIntersection id: intersection_1_1\nLane ids: ['road_0_1_0_0', 'road_0_1_0_1', 'road_1_0_1_0', 'road_1_0_1_1', 'road_1_2_3_0', 'road_1_2_3_1', 'road_2_1_2_0', 'road_2_1_2_1']\nPhase ids: [1, 2, 3, 4, 5, 6, 7, 8]\n\nComparison:\nfixed_cycle                              | reward=  -6621.00 | avg_wait=   45.98 | final_wait=   74.00 | travel_time=   97.49\nbucketed_no_phase_default                | reward=  -5273.00 | avg_wait=   36.62 | final_wait=   57.00 | travel_time=   85.11\nbucketed_no_phase_delta_wait             | reward=  -1721.00 | avg_wait=   11.95 | final_wait=   14.00 | travel_time=   69.02\nbucketed_no_phase_wait_small_vehicle     | reward=  -3586.00 | avg_wait=   24.90 | final_wait=   51.00 | travel_time=   77.66\nbucketed_no_phase_wait_vehicle           | reward=  -4602.00 | avg_wait=   31.96 | final_wait=   45.00 | travel_time=   82.72\ncapped_no_phase_default_reward           | reward=  -5477.00 | avg_wait=   38.03 | final_wait=   48.00 | travel_time=   88.23\ncapped_no_phase_delta_wait               | reward=  -1640.00 | avg_wait=   11.39 | final_wait=   18.00 | travel_time=   66.77\ncapped_no_phase_wait_small_vehicle       | reward=  -5032.00 | avg_wait=   34.94 | final_wait=   60.00 | travel_time=   83.32\ncapped_no_phase_wait_vehicle             | reward=  -5417.00 | avg_wait=   37.62 | final_wait=   54.00 | travel_time=   93.14\nbucketed_with_phase_default_reward       | reward=  -4604.00 | avg_wait=   31.97 | final_wait=   56.00 | travel_time=   85.98\nbucketed_with_phase_delta_wait           | reward=  -1952.00 | avg_wait=   13.56 | final_wait=   12.00 | travel_time=   72.92\nbucketed_with_phase_wait_small_vehicle   | reward=  -5972.00 | avg_wait=   41.47 | final_wait=   66.00 | travel_time=   95.13\nbucketed_with_phase_wait_vehicle         | reward=  -5254.00 | avg_wait=   36.49 | final_wait=   69.00 | travel_time=   88.26\ncapped_with_phase_default_reward         | reward=  -5663.00 | avg_wait=   39.33 | final_wait=   56.00 | travel_time=   89.30\ncapped_with_phase_delta_wait             | reward=  -1566.00 | avg_wait=   10.88 | final_wait=   27.00 | travel_time=   67.60\ncapped_with_phase_wait_small_vehicle     | reward=  -6005.00 | avg_wait=   41.70 | final_wait=   67.00 | travel_time=   89.74\ncapped_with_phase_wait_vehicle           | reward=  -5590.00 | avg_wait=   38.82 | final_wait=   40.00 | travel_time=   94.94\n\nSaved combined comparison:\n  results/hangzhou_comparison/comparison_all_datasets.csv\n")

## 11. Run Stable-Baselines3 Experiments

This section runs DQN, PPO, and A2C scripts if they are present and enabled.

In [20]:
if RUN_STABLE_BASELINES:
    sb3_candidates = [
        "scripts/stable_baselines/train_dqn.py",
        "scripts/stable_baselines/train_ppo.py",
        "scripts/stable_baselines/train_a2c.py",
        "scripts/stable_baselines/compare_sb3_models.py",
    ]
    for candidate in sb3_candidates:
        run_python_script(candidate, required=False)
else:
    print("Skipping Stable-Baselines3 experiments. Set RUN_STABLE_BASELINES=True to run them.")

Skipping Stable-Baselines3 experiments. Set RUN_STABLE_BASELINES=True to run them.

## 12. Run DQN + LSTM Pipeline

This section runs temporal-state experiments if the scripts are available and enabled.

In [21]:
if RUN_DQN_LSTM:
    dqn_lstm_steps = [
        "scripts/dqn_lstm/collect_lstm_data.py",
        "scripts/dqn_lstm/train_lstm.py",
        "scripts/dqn_lstm/train_dqn_with_lstm.py",
    ]
    for step in dqn_lstm_steps:
        run_python_script(step, required=False)
else:
    print("Skipping DQN + LSTM pipeline. Set RUN_DQN_LSTM=True to run it.")

Skipping DQN + LSTM pipeline. Set RUN_DQN_LSTM=True to run it.

## 13. Run LSTM Vector Experiments

This section runs LSTM vector representation experiments if available and enabled.

In [22]:
if RUN_LSTM_VECTOR:
    lstm_vector_candidates = [
        "scripts/lstm_vector/lstm_vector_train.py",
        "scripts/lstm_vector/train_lstm_vector.py",
        "scripts/lstm_vector/evaluate_lstm_vector.py",
    ]
    for candidate in lstm_vector_candidates:
        run_python_script(candidate, required=False)
else:
    print("Skipping LSTM vector experiments. Set RUN_LSTM_VECTOR=True to run them.")

Skipping LSTM vector experiments. Set RUN_LSTM_VECTOR=True to run them.

## 14. Load and Summarize Result CSV Files

This cell reads all CSV files generated in `results/`, displays their final rows, and creates a combined summary table.

In [23]:
import pandas as pd
from IPython.display import display

csv_files = sorted((PROJECT_ROOT / "results").rglob("*.csv"))
print(f"Found {len(csv_files)} CSV file(s).")

summary_rows = []

for csv_file in csv_files:
    try:
        df = pd.read_csv(csv_file)
        print("===", csv_file.relative_to(PROJECT_ROOT), "===")
        display(df.tail(3))

        row = {"file": str(csv_file.relative_to(PROJECT_ROOT)), "rows": len(df)}
        if len(df) > 0:
            last = df.iloc[-1]
            for col in df.columns:
                value = last[col]
                if pd.api.types.is_numeric_dtype(df[col]):
                    row[f"final_{col}"] = value
        summary_rows.append(row)
    except Exception as exc:
        print(f"Could not read {csv_file}: {exc}")

summary_df = pd.DataFrame(summary_rows)
if not summary_df.empty:
    summary_path = PROJECT_ROOT / "results" / "final_comparison_summary.csv"
    summary_df.to_csv(summary_path, index=False)
    print("Saved summary to:", summary_path.relative_to(PROJECT_ROOT))
    display(summary_df)
else:
    print("No result CSVs found yet. Run experiment cells above or check script output paths.")

Found 135 CSV file(s).
=== results/baseline/fixed_ep1.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -56.4           38.0            204        57.385965
38    38     195.0   -52.8           34.0            208        58.164530
39    39     200.0   -52.2           36.0            212        58.922917

=== results/baseline/fixed_ep2.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -56.4           38.0            204        57.385965
38    38     195.0   -52.8           34.0            208        58.164530
39    39     200.0   -52.2           36.0            212        58.922917

=== results/baseline/fixed_ep3.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -56.4           38.0            204        57.385965
38    38     195.0   -52.8           34.0            208        58.164530
39    39     200.0   -52.2           36.0            212        58.922917

=== results/baseline/fixed_ep4.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -56.4           38.0            204        57.385965
38    38     195.0   -52.8           34.0            208        58.164530
39    39     200.0   -52.2           36.0            212        58.922917

=== results/baseline/fixed_ep5.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -56.4           38.0            204        57.385965
38    38     195.0   -52.8           34.0            208        58.164530
39    39     200.0   -52.2           36.0            212        58.922917

=== results/baseline/random_ep1.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -54.8           38.0            208        59.578947
38    38     195.0   -56.0           41.0            210        60.309829
39    39     200.0   -58.4           45.0            214        61.045833

=== results/baseline/random_ep2.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -56.5           39.0            235        61.866228
38    38     195.0   -57.7           39.0            237        62.865385
39    39     200.0   -61.9           45.0            239        63.787500

=== results/baseline/random_ep3.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -42.2           20.0            222        59.140351
38    38     195.0   -51.6           29.0            226        60.066239
39    39     200.0   -56.0           35.0            230        60.968750

=== results/baseline/random_ep4.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -57.2           43.0            212        57.563596
38    38     195.0   -57.0           42.0            220        58.440171
39    39     200.0   -59.8           42.0            228        59.358333

=== results/baseline/random_ep5.csv ===

    step  sim_time  reward  total_waiting  vehicle_count  avg_travel_time
37    37     190.0   -52.7           32.0            217        55.932018
38    38     195.0   -51.9           33.0            219        56.839744
39    39     200.0   -56.7           39.0            227        57.787500

=== results/hangzhou_1x1_bc-tyc_18041607_1h/hangzhou_comparison/comparison_single_run.csv ===

,dataset,method,eval_wait_only_reward,avg_waiting,final_waiting,avg_travel_time
14,hangzhou_1x1_bc-tyc_18041607_1h,capped_with_phase_delta_wait,-581.0,4.034722,7.0,55.360578
15,hangzhou_1x1_bc-tyc_18041607_1h,capped_with_phase_wait_small_vehicle,-4617.0,32.062500,65.0,84.030236
16,hangzhou_1x1_bc-tyc_18041607_1h,capped_with_phase_wait_vehicle,-2315.0,16.076389,25.0,74.635899

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,2,3,0,4,4,3,-54.0,54.0,63,84.113269
142,142,715.0,2,3,0,4,4,3,-58.0,58.0,64,84.323718
143,143,720.0,2,3,0,4,4,3,-58.0,58.0,63,85.063898

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-1370.0,-9.513889,28.0,9.513889,80.469649,0.05
1998,1999,-777.0,-5.395833,16.0,5.395833,72.274760,0.05
1999,2000,-739.0,-5.131944,18.0,5.131944,70.677316,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_delta_wait/training.csv ===

      episode  total_reward  final_waiting  final_avg_travel_time  epsilon
1997     1998          -7.0            7.0              70.539936     0.05
1998     1999          -6.0            6.0              69.801917     0.05
1999     2000          -7.0            7.0              67.373802     0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,7,8,0,2,0,4,-22.4,20.0,48,72.336570
142,142,715.0,6,7,0,2,2,4,-25.4,23.0,48,72.403846
143,143,720.0,7,8,0,2,0,4,-23.3,21.0,46,72.916933

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-1102.05,-7.653125,15.0,6.055556,74.025559,0.05
1998,1999,-1206.00,-8.375000,17.0,6.750000,75.210863,0.05
1999,2000,-1350.15,-9.376042,21.0,7.729167,76.172524,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,2,3,2,4,4,3,-82.8,75.0,78,91.051780
142,142,715.0,2,3,2,4,4,3,-85.1,77.0,81,91.458333
143,143,720.0,2,3,2,4,4,3,-85.2,77.0,82,92.472843

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_no_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2031.0,-14.104167,35.0,10.576389,81.469649,0.05
1998,1999,-1554.1,-10.792361,15.0,7.423611,78.022364,0.05
1999,2000,-1857.1,-12.896528,21.0,9.347222,82.079872,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,0,3,4,1,0,-40.0,40.0,63,92.572816
142,142,715.0,7,8,0,3,3,1,7,-43.0,43.0,64,92.705128
143,143,720.0,3,4,0,3,3,2,3,-42.0,42.0,62,93.412141

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2334.0,-16.208333,33.0,16.208333,98.290735,0.05
1998,1999,-1087.0,-7.548611,29.0,7.548611,77.169329,0.05
1999,2000,-3159.0,-21.937500,47.0,21.937500,112.782748,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,0,2,1,0,5,2.0,4.0,35,69.550162
142,142,715.0,1,2,0,1,1,1,1,-2.0,6.0,34,69.432692
143,143,720.0,7,8,0,2,0,2,7,-1.0,7.0,33,69.747604

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5.0,-0.034722,5.0,4.000000,70.121406,0.05
1998,1999,-9.0,-0.062500,9.0,3.923611,69.287540,0.05
1999,2000,-7.0,-0.048611,7.0,4.270833,70.654952,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,0,4,2,2,0,-27.30,25.0,46,86.789644
142,142,715.0,1,2,0,4,3,2,1,-28.45,26.0,49,86.724359
143,143,720.0,0,1,0,4,3,2,0,-24.30,22.0,46,87.198083

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2225.65,-15.455903,27.0,13.458333,92.300319,0.05
1998,1999,-2326.10,-16.153472,30.0,14.090278,95.405751,0.05
1999,2000,-1879.05,-13.048958,16.0,11.131944,88.677316,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,1,3,4,3,1,-50.8,42.0,88,120.255663
142,142,715.0,1,2,2,3,4,3,1,-51.9,43.0,89,120.519231
143,143,720.0,3,4,3,3,3,4,3,-55.6,47.0,86,121.523962

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_bucketed_with_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2488.0,-17.277778,27.0,13.277778,92.418530,0.05
1998,1999,-2493.9,-17.318750,28.0,13.388889,90.769968,0.05
1999,2000,-2145.2,-14.897222,21.0,11.159722,86.367412,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,3,4,4,10,9,10,-36.0,36.0,65,92.414239
142,142,715.0,4,5,0,10,10,10,-38.0,38.0,66,92.576923
143,143,720.0,0,1,0,10,10,10,-40.0,40.0,63,93.303514

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-1919.0,-13.326389,25.0,13.326389,92.511182,0.05
1998,1999,-3184.0,-22.111111,43.0,22.111111,112.246006,0.05
1999,2000,-2144.0,-14.888889,41.0,14.888889,94.079872,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,0,2,2,0,0.0,4.0,29,66.809061
142,142,715.0,1,2,0,1,3,1,-1.0,5.0,28,66.621795
143,143,720.0,7,8,0,3,0,2,0.0,5.0,28,66.853035

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-8.0,-0.055556,8.0,4.305556,70.194888,0.05
1998,1999,-6.0,-0.041667,6.0,3.465278,67.658147,0.05
1999,2000,-8.0,-0.055556,8.0,3.479167,67.364217,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,5,10,5,1,-26.05,23.0,61,93.278317
142,142,715.0,2,3,5,10,7,6,-33.00,30.0,60,93.346154
143,143,720.0,7,8,5,10,2,7,-31.95,29.0,59,94.000000

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2652.95,-18.423264,37.0,16.284722,98.763578,0.05
1998,1999,-3373.40,-23.426389,47.0,21.069444,108.766773,0.05
1999,2000,-3127.65,-21.719792,29.0,19.375000,108.185304,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,6,10,2,4,-29.7,24.0,57,94.734628
142,142,715.0,4,5,4,10,5,7,-35.0,29.0,60,94.769231
143,143,720.0,7,8,5,10,3,10,-38.7,33.0,57,95.392971

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_no_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-3624.6,-25.170833,23.0,20.486111,108.450479,0.05
1998,1999,-3285.7,-22.817361,39.0,18.270833,104.942492,0.05
1999,2000,-2955.7,-20.525694,40.0,16.333333,96.750799,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,3,10,10,9,1,-38.0,38.0,71,129.333333
142,142,715.0,1,2,3,10,9,10,1,-35.0,35.0,75,129.419872
143,143,720.0,0,1,0,10,8,7,0,-30.0,30.0,75,130.338658

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-3474.0,-24.125000,39.0,24.125000,120.261981,0.05
1998,1999,-3007.0,-20.881944,31.0,20.881944,111.693291,0.05
1999,2000,-2685.0,-18.645833,28.0,18.645833,106.578275,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,6,7,0,1,3,2,6,-2.0,6.0,41,68.980583
142,142,715.0,1,2,0,1,2,2,1,1.0,5.0,40,68.958333
143,143,720.0,3,4,0,2,2,3,3,-2.0,7.0,37,69.345048

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-11.0,-0.076389,11.0,3.604167,68.335463,0.05
1998,1999,-8.0,-0.055556,8.0,4.694444,71.575080,0.05
1999,2000,-12.0,-0.083333,12.0,4.083333,69.370607,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,4,5,3,10,10,4,4,-75.00,71.0,80,130.954693
142,142,715.0,4,5,0,10,10,4,4,-73.15,69.0,83,131.266026
143,143,720.0,1,2,1,10,10,5,1,-69.20,65.0,84,132.440895

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-3473.45,-24.121181,47.0,21.715278,111.293930,0.05
1998,1999,-2174.10,-15.097917,34.0,13.166667,89.230032,0.05
1999,2000,-2396.25,-16.640625,25.0,14.541667,96.980831,0.05

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,0,10,10,4,5,-30.4,25.0,54,99.398058
142,142,715.0,6,7,0,10,10,5,6,-33.7,28.0,57,99.339744
143,143,720.0,3,4,0,7,10,7,3,-30.6,25.0,56,99.920128

=== results/hangzhou_1x1_bc-tyc_18041607_1h/q_learning_capped_with_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-3201.6,-22.233333,38.0,17.763889,103.166134,0.05
1998,1999,-3583.2,-24.883333,38.0,20.097222,110.523962,0.05
1999,2000,-2698.0,-18.736111,16.0,14.534722,97.019169,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/hangzhou_comparison/comparison_single_run.csv ===

,dataset,method,eval_wait_only_reward,avg_waiting,final_waiting,avg_travel_time
14,hangzhou_1x1_bc-tyc_18041608_1h,capped_with_phase_delta_wait,-3818.0,26.513889,39.0,75.804385
15,hangzhou_1x1_bc-tyc_18041608_1h,capped_with_phase_wait_small_vehicle,-7224.0,50.166667,42.0,99.394158
16,hangzhou_1x1_bc-tyc_18041608_1h,capped_with_phase_wait_vehicle,-6894.0,47.875000,62.0,95.482286

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,4,5,3,4,1,2,-65.0,65.0,103,156.095949
142,142,715.0,5,6,3,4,2,0,-64.0,64.0,102,155.930526
143,143,720.0,7,8,3,4,0,1,-63.0,63.0,103,155.804574

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-6600.0,-45.833333,65.0,45.833333,146.486486,0.05
1998,1999,-6910.0,-47.986111,66.0,47.986111,148.151767,0.05
1999,2000,-5180.0,-35.972222,64.0,35.972222,134.542620,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_delta_wait/training.csv ===

      episode  total_reward  final_waiting  final_avg_travel_time  epsilon
1997     1998         -36.0           36.0             117.176715     0.05
1998     1999         -29.0           29.0             113.220374     0.05
1999     2000         -36.0           36.0             104.478170     0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,6,7,4,3,2,0,-70.05,65.0,101,124.473348
142,142,715.0,6,7,4,3,2,0,-64.00,59.0,100,124.507368
143,143,720.0,6,7,4,3,2,0,-61.10,56.0,102,124.571726

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-7023.65,-48.775347,50.0,44.625000,153.259875,0.05
1998,1999,-6081.10,-42.229861,44.0,38.388889,136.914761,0.05
1999,2000,-7376.05,-51.222569,54.0,46.951389,156.220374,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,3,4,4,3,3,2,-120.3,107.0,133,148.833689
142,142,715.0,0,1,4,3,3,1,-114.2,101.0,132,148.696842
143,143,720.0,3,4,4,3,3,1,-115.3,102.0,133,148.596674

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_no_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-7326.4,-50.877778,67.0,42.625000,155.282744,0.05
1998,1999,-7076.5,-49.142361,69.0,41.062500,129.800416,0.05
1999,2000,-7297.3,-50.675694,63.0,42.555556,152.403326,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,3,4,1,1,0,-40.0,40.0,85,144.961620
142,142,715.0,6,7,3,3,2,1,6,-39.0,39.0,86,144.764211
143,143,720.0,6,7,3,3,3,1,6,-40.0,40.0,88,144.607069

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-6082.0,-42.236111,48.0,42.236111,148.324324,0.05
1998,1999,-7089.0,-49.229167,66.0,49.229167,162.027027,0.05
1999,2000,-6079.0,-42.215278,38.0,42.215278,153.806653,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,3,4,2,3,1,-5.0,41.0,88,116.614072
142,142,715.0,6,7,3,3,3,3,6,-2.0,43.0,91,116.332632
143,143,720.0,0,1,3,3,3,2,0,1.0,42.0,93,116.091476

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-32.0,-0.222222,32.0,22.597222,106.532225,0.05
1998,1999,-29.0,-0.201389,29.0,25.645833,115.463617,0.05
1999,2000,-32.0,-0.222222,32.0,28.208333,125.426195,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,7,8,4,4,3,2,7,-45.10,40.0,102,162.226013
142,142,715.0,1,2,4,4,3,2,1,-46.20,41.0,104,161.987368
143,143,720.0,1,2,4,4,2,2,1,-40.35,35.0,107,161.792100

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-6540.45,-45.419792,67.0,41.340278,146.528067,0.05
1998,1999,-5824.55,-40.448264,58.0,36.576389,133.160083,0.05
1999,2000,-7094.75,-49.269097,79.0,44.979167,150.860707,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,4,3,1,2,1,-62.2,52.0,102,142.253731
142,142,715.0,5,6,4,3,2,0,5,-64.2,54.0,102,141.991579
143,143,720.0,7,8,4,3,1,1,7,-63.1,53.0,101,141.754678

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_bucketed_with_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-7286.7,-50.602083,51.0,42.347222,160.226611,0.05
1998,1999,-7591.3,-52.717361,60.0,44.444444,165.413721,0.05
1999,2000,-8194.5,-56.906250,57.0,48.666667,177.862786,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,7,8,9,10,2,9,-49.0,49.0,92,154.144989
142,142,715.0,4,5,8,10,2,9,-52.0,52.0,94,153.943158
143,143,720.0,5,6,8,10,5,4,-51.0,51.0,96,153.787942

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5034.0,-34.958333,37.0,34.958333,143.991684,0.05
1998,1999,-5573.0,-38.701389,49.0,38.701389,144.954262,0.05
1999,2000,-5764.0,-40.027778,50.0,40.027778,159.432432,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,6,7,10,10,8,4,-4.0,44.0,94,118.515991
142,142,715.0,0,1,10,10,10,2,3.0,41.0,95,118.122105
143,143,720.0,1,2,10,10,8,3,3.0,38.0,95,117.760915

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-39.0,-0.270833,39.0,26.520833,114.532225,0.05
1998,1999,-37.0,-0.256944,37.0,27.798611,117.906445,0.05
1999,2000,-37.0,-0.256944,37.0,26.937500,113.810811,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,7,8,10,10,1,3,-62.60,58.0,92,139.724947
142,142,715.0,6,7,10,10,2,3,-55.65,51.0,93,139.570526
143,143,720.0,7,8,10,10,0,3,-50.75,46.0,95,139.457380

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5750.05,-39.930903,35.0,36.201389,146.669439,0.05
1998,1999,-6298.30,-43.738194,53.0,39.701389,146.185031,0.05
1999,2000,-5794.80,-40.241667,41.0,36.493056,152.130977,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,6,10,2,5,-57.1,48.0,91,154.855011
142,142,715.0,7,8,3,10,2,4,-54.0,45.0,90,154.557895
143,143,720.0,1,2,6,10,0,7,-54.2,45.0,92,154.301455

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_no_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-8001.6,-55.566667,49.0,47.145833,168.731809,0.05
1998,1999,-7632.8,-53.005556,49.0,44.791667,162.889813,0.05
1999,2000,-7456.0,-51.777778,64.0,43.652778,162.128898,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,6,10,10,2,1,-56.0,56.0,101,155.217484
142,142,715.0,4,5,4,10,10,2,4,-54.0,54.0,103,155.006316
143,143,720.0,5,6,3,10,10,0,5,-52.0,52.0,103,154.817048

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-6669.0,-46.312500,66.0,46.312500,159.650728,0.05
1998,1999,-5913.0,-41.062500,49.0,41.062500,154.727651,0.05
1999,2000,-6754.0,-46.902778,69.0,46.902778,163.546778,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,10,10,8,3,0,2.0,42.0,92,118.545842
142,142,715.0,1,2,10,10,7,3,1,2.0,40.0,92,118.235789
143,143,720.0,0,1,10,10,9,3,0,1.0,39.0,94,117.966736

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-31.0,-0.215278,31.0,26.354167,117.873181,0.05
1998,1999,-33.0,-0.229167,33.0,30.791667,126.108108,0.05
1999,2000,-41.0,-0.284722,41.0,26.465278,118.359667,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,7,10,10,8,1,-61.2,56.0,104,177.076759
142,142,715.0,7,8,7,10,10,8,7,-53.3,48.0,106,176.917895
143,143,720.0,7,8,7,10,7,8,7,-47.4,42.0,108,176.806653

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-7046.05,-48.930903,59.0,44.645833,158.916840,0.05
1998,1999,-7751.00,-53.826389,51.0,49.458333,177.299376,0.05
1999,2000,-7802.40,-54.183333,71.0,49.805556,170.679834,0.05

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,4,5,3,10,10,7,4,-81.7,70.0,117,167.829424
142,142,715.0,1,2,5,10,10,7,1,-78.6,67.0,116,167.623158
143,143,720.0,2,3,7,10,10,6,2,-73.7,62.0,117,167.451143

=== results/hangzhou_1x1_bc-tyc_18041608_1h/q_learning_capped_with_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-7823.8,-54.331944,41.0,45.909722,170.051975,0.05
1998,1999,-8387.3,-58.245139,43.0,49.618056,173.906445,0.05
1999,2000,-8632.6,-59.948611,51.0,51.222222,177.203742,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/hangzhou_comparison/comparison_single_run.csv ===

,dataset,method,eval_wait_only_reward,avg_waiting,final_waiting,avg_travel_time
14,hangzhou_1x1_bc-tyc_18041610_1h,capped_with_phase_delta_wait,-1566.0,10.875000,27.0,67.598218
15,hangzhou_1x1_bc-tyc_18041610_1h,capped_with_phase_wait_small_vehicle,-6005.0,41.701389,67.0,89.735919
16,hangzhou_1x1_bc-tyc_18041610_1h,capped_with_phase_wait_vehicle,-5590.0,38.819444,40.0,94.943831

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,3,4,0,4,-57.0,57.0,98,131.221945
142,142,715.0,4,5,2,4,0,4,-59.0,59.0,98,131.054187
143,143,720.0,0,1,2,4,0,4,-57.0,57.0,99,132.199017

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2844.0,-19.750000,41.0,19.750000,98.756757,0.05
1998,1999,-2641.0,-18.340278,31.0,18.340278,95.039312,0.05
1999,2000,-2024.0,-14.055556,39.0,14.055556,86.135135,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_delta_wait/training.csv ===

      episode  total_reward  final_waiting  final_avg_travel_time  epsilon
1997     1998         -25.0           25.0              88.948403     0.05
1998     1999         -25.0           25.0              85.894349     0.05
1999     2000         -23.0           23.0              88.179361     0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,6,7,3,3,3,4,-54.4,50.0,88,106.201995
142,142,715.0,6,7,3,2,3,4,-55.4,51.0,88,105.972906
143,143,720.0,4,5,3,2,3,4,-55.3,51.0,86,106.771499

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-4032.4,-28.002778,46.0,25.020833,107.651106,0.05
1998,1999,-3590.7,-24.935417,48.0,22.090278,101.835381,0.05
1999,2000,-4015.9,-27.888194,49.0,24.888889,107.297297,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,4,3,1,4,-45.7,36.0,97,123.251870
142,142,715.0,3,4,4,3,1,4,-48.8,39.0,98,123.123153
143,143,720.0,3,4,4,3,2,4,-54.5,45.0,95,124.189189

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_no_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-4815.6,-33.441667,45.0,27.118056,113.009828,0.05
1998,1999,-4394.2,-30.515278,59.0,24.520833,107.171990,0.05
1999,2000,-4426.6,-30.740278,51.0,24.652778,108.992629,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,3,4,3,3,3,2,3,-51.0,51.0,94,128.778055
142,142,715.0,0,1,3,4,4,1,0,-55.0,55.0,95,128.640394
143,143,720.0,5,6,3,4,4,0,5,-56.0,56.0,93,129.766585

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5283.0,-36.687500,57.0,36.687500,133.874693,0.05
1998,1999,-4340.0,-30.138889,57.0,30.138889,120.213759,0.05
1999,2000,-4687.0,-32.548611,41.0,32.548611,122.727273,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,1,3,1,1,0,2.0,13.0,58,91.339152
142,142,715.0,6,7,2,3,1,2,6,-2.0,15.0,61,90.950739
143,143,720.0,0,1,2,3,1,1,0,3.0,12.0,59,91.459459

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-23.0,-0.159722,23.0,17.340278,99.972973,0.05
1998,1999,-23.0,-0.159722,23.0,16.048611,96.921376,0.05
1999,2000,-24.0,-0.166667,24.0,16.187500,95.904177,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,2,3,3,2,5,-71.50,66.0,110,141.663342
142,142,715.0,4,5,1,4,3,1,4,-71.60,66.0,112,141.522167
143,143,720.0,0,1,1,4,3,0,0,-71.45,66.0,109,142.764128

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5366.70,-37.268750,50.0,33.909722,131.230958,0.05
1998,1999,-5204.35,-36.141319,62.0,32.819444,122.928747,0.05
1999,2000,-5098.25,-35.404514,56.0,31.979167,123.899263,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_bucket,state_east_bucket,state_south_bucket,state_west_bucket,state_phase_bucket,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,4,3,3,2,5,-74.9,63.0,119,128.690773
142,142,715.0,5,6,4,4,3,0,5,-76.8,65.0,118,128.637931
143,143,720.0,2,3,4,4,3,1,2,-80.8,69.0,118,129.835381

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_bucketed_with_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5755.9,-39.971528,55.0,33.125000,123.31941,0.05
1998,1999,-5111.1,-35.493750,58.0,28.951389,116.97543,0.05
1999,2000,-5823.7,-40.442361,44.0,33.673611,127.87715,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,8,10,10,2,-52.0,52.0,104,134.610973
142,142,715.0,6,7,10,10,10,5,-52.0,52.0,106,134.413793
143,143,720.0,0,1,7,10,10,4,-48.0,48.0,103,135.523342

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-4585.0,-31.840278,64.0,31.840278,121.316953,0.05
1998,1999,-4799.0,-33.326389,48.0,33.326389,128.938575,0.05
1999,2000,-4622.0,-32.097222,62.0,32.097222,121.938575,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,4,5,1,9,1,5,1.0,16.0,59,83.241895
142,142,715.0,1,2,5,9,0,6,-4.0,20.0,59,82.940887
143,143,720.0,4,5,1,10,0,7,2.0,18.0,59,83.461916

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-18.0,-0.125000,18.0,10.534722,82.211302,0.05
1998,1999,-22.0,-0.152778,22.0,14.812500,92.307125,0.05
1999,2000,-20.0,-0.138889,20.0,10.937500,83.621622,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,0,1,10,9,10,9,-69.35,64.0,107,125.154613
142,142,715.0,6,7,10,7,10,9,-68.35,63.0,107,125.216749
143,143,720.0,7,8,10,6,9,10,-65.25,60.0,105,126.498771

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5468.15,-37.973264,47.0,34.583333,129.980344,0.05
1998,1999,-5316.35,-36.919097,46.0,33.493056,130.162162,0.05
1999,2000,-4963.30,-34.467361,50.0,31.055556,122.147420,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,5,6,10,10,5,6,-55.5,45.0,105,138.413965
142,142,715.0,4,5,6,10,8,9,-58.7,48.0,107,138.330049
143,143,720.0,7,8,10,10,4,10,-64.5,54.0,105,139.589681

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_no_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-6055.1,-42.049306,55.0,34.979167,131.764128,0.05
1998,1999,-5582.6,-38.768056,48.0,31.930556,124.017199,0.05
1999,2000,-5044.4,-35.030556,47.0,28.611111,116.454545,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_default_reward/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,1,2,10,10,0,6,1,-55.0,55.0,109,134.541147
142,142,715.0,1,2,10,10,0,10,1,-57.0,57.0,107,134.482759
143,143,720.0,3,4,10,10,1,10,3,-56.0,56.0,106,135.749386

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_default_reward/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-5442.0,-37.791667,67.0,37.791667,135.270270,0.05
1998,1999,-4379.0,-30.409722,67.0,30.409722,118.678133,0.05
1999,2000,-5157.0,-35.812500,53.0,35.812500,130.921376,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_delta_wait/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,2,3,1,10,3,2,2,2.0,21.0,60,82.264339
142,142,715.0,1,2,5,10,2,5,1,-4.0,25.0,62,82.004926
143,143,720.0,2,3,6,10,2,6,2,-2.0,27.0,60,82.545455

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_delta_wait/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-32.0,-0.222222,32.0,16.277778,93.909091,0.05
1998,1999,-24.0,-0.166667,24.0,13.458333,88.621622,0.05
1999,2000,-26.0,-0.180556,26.0,15.347222,93.255528,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_wait_small_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,7,8,10,10,10,10,7,-72.00,66.0,120,140.256858
142,142,715.0,5,6,10,10,10,8,5,-74.95,69.0,119,140.147783
143,143,720.0,6,7,10,10,10,7,6,-72.95,67.0,119,141.417690

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_wait_small_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-6396.45,-44.419792,68.0,40.631944,140.405405,0.05
1998,1999,-4954.55,-34.406597,65.0,31.076389,119.147420,0.05
1999,2000,-5749.80,-39.929167,68.0,36.381944,129.616708,0.05

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_wait_vehicle/q_learning_trace.csv ===

,decision_step,time,action,phase_id,state_north_count,state_east_count,state_south_count,state_west_count,state_phase,reward,total_waiting,vehicle_count,avg_travel_time
141,141,710.0,2,3,10,10,2,5,2,-53.2,44.0,92,138.037406
142,142,715.0,6,7,10,10,2,8,6,-55.3,46.0,93,137.768473
143,143,720.0,0,1,10,10,2,9,0,-49.1,40.0,91,138.850123

=== results/hangzhou_1x1_bc-tyc_18041610_1h/q_learning_capped_with_phase_wait_vehicle/q_learning_training.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-4425.4,-30.731944,59.0,24.784722,106.265356,0.05
1998,1999,-6559.8,-45.554167,72.0,38.243056,137.476658,0.05
1999,2000,-6078.6,-42.212500,56.0,35.020833,130.351351,0.05

=== results/hangzhou_comparison/comparison_all_datasets.csv ===

,dataset,method,eval_wait_only_reward,avg_waiting,final_waiting,avg_travel_time
48,hangzhou_1x1_bc-tyc_18041610_1h,capped_with_phase_delta_wait,-1566.0,10.875000,27.0,67.598218
49,hangzhou_1x1_bc-tyc_18041610_1h,capped_with_phase_wait_small_vehicle,-6005.0,41.701389,67.0,89.735919
50,hangzhou_1x1_bc-tyc_18041610_1h,capped_with_phase_wait_vehicle,-5590.0,38.819444,40.0,94.943831

=== results/hangzhou_comparison/comparison_single_run.csv ===

,method,eval_wait_only_reward,avg_waiting,final_waiting,avg_travel_time
14,capped_with_phase_delta_wait,-581.0,4.034722,7.0,55.360578
15,capped_with_phase_wait_small_vehicle,-4617.0,32.062500,65.0,84.030236
16,capped_with_phase_wait_vehicle,-2315.0,16.076389,25.0,74.635899

=== results/q_learning_bucketed_no_phase_default_reward/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_no_phase_default_reward,-1817.0,58.0,12.618056,85.063898,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_no_phase_default_reward,-6189.0,63.0,42.979167,155.804574,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_no_phase_default_reward,-5273.0,57.0,36.618056,132.199017,144

=== results/q_learning_bucketed_no_phase_delta_wait/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,final_avg_travel_time
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_no_phase_delta_wait,-21.0,21.0,76.862620
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_no_phase_delta_wait,-26.0,26.0,119.642412
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_no_phase_delta_wait,-14.0,14.0,85.375921

=== results/q_learning_bucketed_no_phase_wait_small_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_no_phase_wait_small_vehicle,-1132.40,21.0,6.291667,72.916933,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_no_phase_wait_small_vehicle,-5231.85,56.0,32.888889,124.571726,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_no_phase_wait_small_vehicle,-4015.70,51.0,24.902778,106.771499,144

=== results/q_learning_bucketed_no_phase_wait_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_no_phase_wait_vehicle,-3018.4,77.0,16.951389,92.472843,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_no_phase_wait_vehicle,-7943.4,102.0,46.541667,148.596674,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_no_phase_wait_vehicle,-5558.3,45.0,31.958333,124.189189,144

=== results/q_learning_bucketed_with_phase_default_reward/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_with_phase_default_reward,-2168.0,42.0,15.055556,93.412141,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_with_phase_default_reward,-5299.0,40.0,36.798611,144.607069,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_with_phase_default_reward,-4604.0,56.0,31.972222,129.766585,144

=== results/q_learning_bucketed_with_phase_delta_wait/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_with_phase_delta_wait,-7.0,7.0,4.013889,69.747604,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_with_phase_delta_wait,-42.0,42.0,26.194444,116.091476,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_with_phase_delta_wait,-12.0,12.0,13.555556,91.459459,144

=== results/q_learning_bucketed_with_phase_wait_small_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_with_phase_wait_small_vehicle,-1833.55,22.0,10.847222,87.198083,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_with_phase_wait_small_vehicle,-6756.45,35.0,42.826389,161.792100,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_with_phase_wait_small_vehicle,-6522.05,66.0,41.472222,142.764128,144

=== results/q_learning_bucketed_with_phase_wait_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_bucketed_with_phase_wait_vehicle,-4658.0,47.0,27.076389,121.523962,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_bucketed_with_phase_wait_vehicle,-7093.9,53.0,41.048611,141.754678,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_bucketed_with_phase_wait_vehicle,-6293.4,69.0,36.486111,129.835381,144

=== results/q_learning_capped_no_phase_default_reward/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_no_phase_default_reward,-2127.0,40.0,14.770833,93.303514,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_no_phase_default_reward,-5955.0,51.0,41.354167,153.787942,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_no_phase_default_reward,-5477.0,48.0,38.034722,135.523342,144

=== results/q_learning_capped_no_phase_delta_wait/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_no_phase_delta_wait,-5.0,5.0,3.118056,66.853035,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_no_phase_delta_wait,-38.0,38.0,29.020833,117.760915,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_no_phase_delta_wait,-18.0,18.0,11.388889,83.461916,144

=== results/q_learning_capped_no_phase_wait_small_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_no_phase_wait_small_vehicle,-2292.85,29.0,13.888889,94.000000,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_no_phase_wait_small_vehicle,-5761.55,46.0,36.312500,139.457380,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_no_phase_wait_small_vehicle,-5518.10,60.0,34.944444,126.498771,144

=== results/q_learning_capped_no_phase_wait_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_no_phase_wait_vehicle,-2735.1,33.0,14.861111,95.392971,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_no_phase_wait_vehicle,-7012.4,45.0,40.791667,154.301455,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_no_phase_wait_vehicle,-6462.4,54.0,37.618056,139.589681,144

=== results/q_learning_capped_with_phase_default_reward/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_with_phase_default_reward,-4017.0,30.0,27.895833,130.338658,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_with_phase_default_reward,-6267.0,52.0,43.520833,154.817048,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_with_phase_default_reward,-5663.0,56.0,39.326389,135.749386,144

=== results/q_learning_capped_with_phase_delta_wait/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_with_phase_delta_wait,-7.0,7.0,4.034722,69.345048,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_with_phase_delta_wait,-39.0,39.0,26.513889,117.966736,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_with_phase_delta_wait,-27.0,27.0,10.875000,82.545455,144

=== results/q_learning_capped_with_phase_wait_small_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_with_phase_wait_small_vehicle,-5018.00,65.0,32.062500,132.440895,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_with_phase_wait_small_vehicle,-7832.20,42.0,50.166667,176.806653,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_with_phase_wait_small_vehicle,-6566.65,67.0,41.701389,141.417690,144

=== results/q_learning_capped_with_phase_wait_vehicle/summary_all_datasets.csv ===

,dataset,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions
0,hangzhou_1x1_bc-tyc_18041607_1h,q_learning_capped_with_phase_wait_vehicle,-2938.3,25.0,16.076389,99.920128,144
1,hangzhou_1x1_bc-tyc_18041608_1h,q_learning_capped_with_phase_wait_vehicle,-8142.1,62.0,47.875000,167.451143,144
2,hangzhou_1x1_bc-tyc_18041610_1h,q_learning_capped_with_phase_wait_vehicle,-6673.1,40.0,38.819444,138.850123,144

=== results/reward_experiments/comparison_delta_wait.csv ===

,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions,run
37,q_learning,-158.0,158.0,72.65,60.69375,40,18
38,q_learning,-158.0,158.0,72.65,60.69375,40,19
39,q_learning,-158.0,158.0,72.65,60.69375,40,20

=== results/reward_experiments/comparison_wait_only.csv ===

,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions,run
37,q_learning,-2918.0,153.0,72.95,60.98125,40,18
38,q_learning,-2918.0,153.0,72.95,60.98125,40,19
39,q_learning,-2918.0,153.0,72.95,60.98125,40,20

=== results/reward_experiments/comparison_wait_small_vehicle.csv ===

,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions,run
37,q_learning,-3217.65,158.0,73.2,60.977083,40,18
38,q_learning,-3217.65,158.0,73.2,60.977083,40,19
39,q_learning,-3217.65,158.0,73.2,60.977083,40,20

=== results/reward_experiments/comparison_wait_vehicle.csv ===

,method,total_reward,final_waiting,avg_waiting,final_avg_travel_time,num_decisions,run
37,q_learning,-3503.0,156.0,73.1,61.027083,40,18
38,q_learning,-3503.0,156.0,73.1,61.027083,40,19
39,q_learning,-3503.0,156.0,73.1,61.027083,40,20

=== results/reward_experiments/reward_experiments_summary.csv ===

,reward_variant,mean_total_reward,mean_final_waiting,mean_avg_waiting,mean_avg_travel_time,baseline_mean_total_reward,baseline_mean_final_waiting,baseline_mean_avg_waiting,baseline_mean_avg_travel_time
1,wait_vehicle,-3503.00,156.0,73.10,61.027083,-3458.70,151.0,72.1,60.445833
2,wait_small_vehicle,-3217.65,158.0,73.20,60.977083,-3171.35,151.0,72.1,60.445833
3,delta_wait,-158.00,158.0,72.65,60.693750,-151.00,151.0,72.1,60.445833

=== results/reward_experiments/training_delta_wait.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-155.0,-3.875,155.0,73.150,60.893750,0.05
1998,1999,-158.0,-3.950,158.0,72.650,60.693750,0.05
1999,2000,-153.0,-3.825,153.0,72.475,60.645833,0.05

=== results/reward_experiments/training_wait_only.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-2956.0,-73.900,156.0,73.900,61.279167,0.05
1998,1999,-2937.0,-73.425,157.0,73.425,61.279167,0.05
1999,2000,-2928.0,-73.200,153.0,73.200,61.104167,0.05

=== results/reward_experiments/training_wait_small_vehicle.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-3198.30,-79.95750,151.0,72.725,60.891667,0.05
1998,1999,-3217.65,-80.44125,158.0,73.200,60.977083,0.05
1999,2000,-3202.30,-80.05750,156.0,72.825,60.891667,0.05

=== results/reward_experiments/training_wait_vehicle.csv ===

,episode,total_reward,mean_reward_per_decision,final_waiting,avg_waiting,final_avg_travel_time,epsilon
1997,1998,-3551.5,-88.7875,156.0,74.2,61.425000,0.05
1998,1999,-3503.0,-87.5750,156.0,73.1,61.027083,0.05
1999,2000,-3503.3,-87.5825,154.0,73.1,61.029167,0.05

=== results/stable_baselines/sb3_comparison.csv ===

,model,mean_total_reward,mean_final_waiting,mean_avg_waiting,mean_avg_travel_time
0,dqn,-2965.6,153.0,71.075,60.233333
1,ppo,-3066.1,155.0,73.400,61.125000
2,a2c,-3675.9,208.0,90.175,65.066667

=== results/stable_baselines/sb3_comparison_all_datasets_states_rewards.csv ===

,dataset,model,state_mode,reward_mode,mean_total_reward,mean_final_waiting,mean_avg_waiting,mean_avg_travel_time
141,hangzhou_1x1_bc-tyc_18041610_1h,dqn,bucketed_with_phase,delta_wait,-20.0,20.0,12.701389,87.990172
142,hangzhou_1x1_bc-tyc_18041610_1h,ppo,bucketed_with_phase,delta_wait,-23.0,23.0,11.125000,81.265356
143,hangzhou_1x1_bc-tyc_18041610_1h,a2c,bucketed_with_phase,delta_wait,-25.0,25.0,13.041667,85.461916

Saved summary to: results/final_comparison_summary.csv

,file,rows,final_step,final_sim_time,final_reward,final_total_waiting,final_vehicle_count,final_avg_travel_time,final_eval_wait_only_reward,final_avg_waiting,...,final_num_decisions,final_run,final_mean_total_reward,final_mean_final_waiting,final_mean_avg_waiting,final_mean_avg_travel_time,final_baseline_mean_total_reward,final_baseline_mean_final_waiting,final_baseline_mean_avg_waiting,final_baseline_mean_avg_travel_time
0,results/baseline/fixed_ep1.csv,40,39.0,200.0,-52.2,36.0,212.0,58.922917,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,results/baseline/fixed_ep2.csv,40,39.0,200.0,-52.2,36.0,212.0,58.922917,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,results/baseline/fixed_ep3.csv,40,39.0,200.0,-52.2,36.0,212.0,58.922917,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,results/baseline/fixed_ep4.csv,40,39.0,200.0,-52.2,36.0,212.0,58.922917,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,results/baseline/fixed_ep5.csv,40,39.0,200.0,-52.2,36.0,212.0,58.922917,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,results/reward_experiments/training_wait_only.csv,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,results/reward_experiments/training_wait_small...,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,results/reward_experiments/training_wait_vehic...,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,results/stable_baselines/sb3_comparison.csv,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-3675.9,208.0,90.175000,65.066667,NaN,NaN,NaN,NaN
134,results/stable_baselines/sb3_comparison_all_da...,144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-25.0,25.0,13.041667,85.461916,NaN,NaN,NaN,NaN

## 15. Generate Final Comparison Plot

This cell creates a simple final comparison chart from the combined summary when numeric result columns are available.

In [ ]:
import matplotlib.pyplot as plt

if 'summary_df' in globals() and not summary_df.empty:
    numeric_cols = [col for col in summary_df.columns if col.startswith("final_") and pd.api.types.is_numeric_dtype(summary_df[col])]
    print("Numeric final metric columns:", numeric_cols)

    if numeric_cols:
        metric = numeric_cols[0]
        plot_df = summary_df[["file", metric]].dropna().copy()
        if not plot_df.empty:
            plot_df = plot_df.sort_values(metric)
            plt.figure(figsize=(12, max(4, 0.35 * len(plot_df))))
            plt.barh(plot_df["file"], plot_df[metric])
            plt.xlabel(metric)
            plt.ylabel("Experiment result file")
            plt.title(f"Final comparison by {metric}")
            plt.tight_layout()
            output_path = PROJECT_ROOT / "figures" / "final_comparison_plot.png"
            plt.savefig(output_path, dpi=200)
            plt.show()
            print("Saved plot to:", output_path.relative_to(PROJECT_ROOT))
        else:
            print("No non-null values available for plotting.")
    else:
        print("No numeric final metrics found for plotting.")
else:
    print("summary_df is empty or unavailable.")

## 17. Reproducibility Checklist

By the end of this notebook, verify that:

1. The Conda environment was created from `environment.yml`.
2. CityFlow installed and imported successfully.
3. `CityFlowEnv` imported successfully.
4. Experiment scripts were discovered under `scripts/`.
5. Result CSV files were generated or loaded from `results/`.
6. A final comparison summary was saved to `results/final_comparison_summary.csv`.

For a quick smoke test, keep `QUICK_RUN = True`. For the full reproducibility run, set `QUICK_RUN = False` and enable the experiment families you want to run.